### ISSUE TITLE
no new notification rules possible

### ISSUE THREAD

**Issue by mc-marcy** [reportportal/migrations#230]
Hi,

since this merge https://github.com/reportportal/migrations/pull/225/files the user can not create new notification rules.

Error Message in postgres is
```
2022-08-10 13:12:30.126 UTC [103] ERROR:  null value in column "rule_name" violates not-null constraint
2022-08-10 13:12:30.126 UTC [103] DETAIL:  Failing row contains (116, ALWAYS, 89, f, null).
2022-08-10 13:12:30.126 UTC [103] STATEMENT:  insert into sender_case (enabled, project_id, send_case) values ($1, $2, $3)
        RETURNING *
```
rule_name can not be null but it is null every time.

reportportal version 5.7.2 and postgres 12
i checked it without the Alter not null comand and it is working then, but not sure what will happen in the future if rule_name is NULL.

any idea?
thanks a lot

**Comment by mc-marcy** [comment]
our customer were asking again. any new info's? progress?

**Comment by miracle8484** [comment]
Hello, @mc-marcy, could you provide more details, what did you do to get this errors?
Try to create notification- from UI or by API? What data did you send exactly?

**Comment by mc-marcy** [comment]
hi @miracle8484 found a few days ago out, that my database was on level 62 which includes this error here. a fresh installation is still on migration level 59. and on this level it works.

but was via ui and api

**Comment by miracle8484** [comment]
> hi @miracle8484 found a few days ago out, that my database was on level 62 which includes this error here. a fresh installation is still on migration level 59. and on this level it works.
> 
> but was via ui and api

ok, thx.
Than i will close this issue.
